import org.springframework.boot.gradle.tasks.bundling.BootJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("se.magnus.microservices.kotlin-application-conventions")
}

tasks.named<BootJar>("bootJar") {
    enabled = false
}

dependencies {
    implementation(project(":api"))
}
